### ISSUE TITLE
Readme links to the wrong documentation

### ISSUE THREAD

**Issue by vmrose** [UPGcarts/clientlibrary#1]
The README.md file is linking to the wrong API Documentation.
Also I would link to it right at the start to allow users to better understand the library **together** with the documentation.

**Comment by vmrose** [comment]
I'd do a pull request to fix it, but I don't have permission of course.

**Comment by CJamies** [comment]
Thanks vincent. I will send you the pwd

**Comment by CJamies** [comment]
Michael is off now for 2 weeks

**Comment by vmrose** [comment]
Thanks for merging the pull request and this issue is resolved.
