### ISSUE TITLE
Monolog Version not up to date

### ISSUE THREAD

**Issue by shartmannhygi** [UPGcarts/clientlibrary#3]
Hi,

we need your Library to implements some payment tools, but your current Monolog version is maximum 1.18.0, we need 1.18.1.

Can you fix the Version?

Thanks :)

**Comment by edmondscommerce** [comment]
Updated the Monolog requirement to anything from 1.16 to 1.20

**Comment by edmondscommerce** [comment]
Updated the Monolog requirement to anything from 1.16 to 1.20
